fail_on_severity: 'critical'
allow_licenses:
  - 'MIT'
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'ISC'
  - 'Unlicense'
  - 'CC0-1.0'
deny_licenses:
  - 'GPL-3.0'
  - 'AGPL-3.0'
  - 'LGPL-3.0'
  - 'GPL-2.0'
deny_groups:
  - 'npm:malicious'
vulnerability_check: true
config_file_path: './.github/dependency-review-config.yml'
