blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://devoirsitech.atlassian.net/wiki/x/AYAP
    about: Merci de consulter la documentation avant de créer une nouvelle issue.
