name: Restrict branch names

on:
  workflow_call:
    
  create:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  restrict-branch-names:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: tj-actions/branch-names@v8
        id: branch-names
      - name: Enforce branch naming convention
        run: |
          BRANCH_NAME="${{ github.event_name == 'pull_request' && github.head_ref || steps.branch-names.current_branch }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feat/|fix/|hotfix/) ]]; then
            echo "Erreur : le nom de la branche doit commencer par feat/, fix/ ou hotfix/."
            exit 1
          fi
